### ISSUE TITLE
user_sessions/new

### ISSUE THREAD

**Issue by Toshiki003** [Toshiki003/Dressing-for-2-years-old-child#22]
## Todo
sorceryのWikiを見ながらログイン・ログアウト機能を実装
参考：https://github.com/Sorcery/sorcery/wiki/Simple-Password-Authentication

- [x] `rails g controller UserSessions new`
- [x] User_sessionコントローラにnew, create, destroyアクションを記述
- [x] user_sessions/new.html.erbファイルにフォーム記述
- [x] routes記述
- [x] コントローラのフィルタ(require_login)設定
画面遷移図が視覚的に分かりやすかった。利用規約などのstatic_pagesを実装したときは、こちらのフィルタをskipする記述を忘れないようにする。
- [x] フラッシュメッセージのパーシャル作成
- [x] フラッシュメッセージがBootstrapが当たるように設定
- [ ] エラーメッセージのパーシャル作成
- [ ] Bootstrap適用

### RSpec関係

- [x] capybaraを`spec/support`配下へ。ドライバにはheadlessChromeを指定
- [x] ログインマクロを作成。 `spec/support/login_macros.rb` にModuleを定義
- [x] `spec/rails_helper.rb`でModuleを読み込む設定を忘れずにする。

システムテスト(users_spec, user_sessions_specの２種類)については、別のissueを立てます。
