### ISSUE TITLE
翻訳ファイル追加・i18n対応

### ISSUE THREAD

**Issue by Toshiki003** [Toshiki003/Dressing-for-2-years-old-child#26]
## Todo
systemテスト前にフォームの翻訳が当たるようにしておきたいと考え実装します。
ユーザー登録、ログイン、トップページのビューが回る状態で翻訳をします。（実装タイミングの是非はPF作り終わってから振り返る予定）

- [x] locales/activerecord/ja.ymlファイルを作成し翻訳記述
- [x] locales/views/ja.ymlファイルを作成し翻訳記述
### 各ビューファイルが翻訳されているようにコードを書き換える

- [x] top
- [x] users/new
- [x] /login
- [x] header
- [x] before_login_header
- [x] footer
