### ISSUE TITLE
Bootstrap CSSの導入

### ISSUE THREAD

**Issue by Toshiki003** [Toshiki003/Dressing-for-2-years-old-child#9]
## Todo
rails new時にcssオプションでbootstrapを入れ忘れてしまったので、今回は後からRails7にBootstrap5系を導入する。

- [x] 仮のtopページを表示させる（Bootstrapが反映されるか確認するため）
  - [x] rails g controller static_pages top
  - [x] routes.rb　root to: 'static_pages#top'

以下の記事を参考に進める。
[[Rails7] 後からBootstrap5を導入する](https://qiita.com/PJZ9n/items/03341f942c2c84713c99)
- [x]  cssbundling-rails gemをインストールする
  - [x] `bundle add cssbundling-rails`
- [x] Bootstrap5(CSS)をインストールする
  - [x] `rails css:install:bootstrap`
- [x] sassのコンパイル用スクリプトを追加→こちらは自分のローカル環境では自動で追加されていた。
- [x] Bootstrap5を導入する
  - [x] `ruby bin/importmap pin bootstrap`
- [x] Popper.jsを導入する(importmap.rbファイル内)
  - [x] - `pin "@popperjs/core", to: "https://ga.jspm.io/npm:@popperjs/core@2.11.2/lib/index.js"`
  - [x] + `pin "@popperjs/core", to: "https://unpkg.com/@popperjs/core@2.11.2/dist/esm/index.js"`
- [x] CSSをビルドする
  - [x] `yarn build:css`
  - [x] `yarn build:css --watch`

- [x] 動作確認
  - [x] topにドロップダウンを設置して正常に表示されるか確認。
  *Qiita記事内にあるForemanを使う(任意)は使用しなかった。

 
以降、記事を参考に進めてみる。
エラーには以下の記事も参考にして進める。
https://note.com/y0419y/n/nb06a1cc2f7e8
https://zenn.dev/shurijo_dot_com/scraps/5880ba7b58d3b1
